name: test
uid: uuid-of-etcd-resource
serviceName: test
configMapName: test

replicas: 1
#priorityClassName: foo

tlsServerSecret: etcd-server-tls
tlsClientSecret: etcd-client-tls
tlsCASecret: ca-etcd
annotations: {}
labels: {}

etcd:
  initialClusterToken: initial
  initialClusterState: new
  enableTLS: false
  pullPolicy: IfNotPresent
  metrics: basic
  clientPort: 2379
  serverPort: 2380
  resources:
    limits:
      cpu: 100m
      memory: 512Gi
    requests:
      cpu: 50m
      memory: 128Mi
  #username: username
  #password: password

backup:
  port: 8080
  pullPolicy: IfNotPresent
  snapstoreTempDir: "/var/etcd/data/temp"
  etcdConnectionTimeout: 5m
  etcdQuotaBytes: 8Gi
  garbageCollectionPolicy: LimitBased
  maxBackups: 7
  resources:
    limits:
      cpu: 100m
      memory: 512Gi
    requests:
      cpu: 50m
      memory: 128Mi
  httpProxy:
  noProxy:
  # compression:
  #   enabled: true
  #   policy: "gzip"

# sharedConfig defines parameters shared and used by Etcd as well as backup-restore sidecar.
sharedConfig:
  # autoCompaction defines the specification to be used by Etcd as well as by embedded-Etcd of backup-restore sidecar during restoration.
  # auto-compaction mode: 'periodic' mode or 'revision' mode for etcd as well as for embedded-Etcd of backup-restore sidecar.
  # auto-compaction retention length for etcd as well as for embedded-Etcd of backup-restore sidecar.
  autoCompactionMode: periodic
  autoCompactionRetention: "30m"


volumeClaimTemplateName: test
storageClass: ""
storageCapacity: 16Gi

store:
  storageProvider: ""
  storePrefix: ""
  storageContainer: ""
